apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels: # TODO Could probably hoist this to some common spsace
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.sentinel.port }}
    protocol: TCP
    targetPort: sentinel
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}